# Alpha Vantage API credentials
# Sign up for a free API key at: https://www.alphavantage.co/support/#api-key
ALPHA_VANTAGE_API_KEY = "YOUR_API_KEY_HERE"

# Note: Keep your API keys secret and never commit this file to version control
# This file should be in .gitignore
